name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy-afood:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to afood
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AFOOD_HOST }}
          username: afood
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /home/afood/a-food.com.ua/okn
            git pull origin main
            php artisan config:clear
            php artisan view:clear

  deploy-shinshin:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to ufit
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SHINSHIN_HOST }}
          username: shinshin
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /home/shinshin/u-fit.com.ua/crm
            git pull origin main
            php artisan config:clear
            php artisan view:clear

  deploy-horenko:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to horenko-production (new server)
        uses: appleboy/ssh-action@master
        with:
          host: 88.99.169.99
          username: root
          key: ${{ secrets.HORENKO_SSH_KEY }}
          script: /usr/local/bin/crm-deploy